
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:1034822545601:android:60241a2aa5e1d5fc44a440",
      firebase_cli_token:"1//03gliYCV-0o_7CgYIARAAGAMSNwF-L9IrQ38FH5sRXc3kvLHaA2ctGRWljYqTeqdanYYbMtORB2DCXqB6PJuIjRU21oca3dEMjiE ",
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mohamed88rshad@gmail.com",
      release_notes: "first fastlane distribution"
    )
  end

end
